Installing packages

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("drug-adverse-effect.csv")
df.head()

safetyreportid primarysourcecountry  serious  seriousnessdeath  \
0       20401550                   US        2               2.0   
1       20719436                   US        2               2.0   
2       20983728                   US        1               2.0   
3       20401631                   US        2               2.0   
4       20719827                   US        1               2.0   

   seriousnesslifethreatening  seriousnesshospitalization  \
0                         2.0                         2.0   
1                         2.0                         2.0   
2                         2.0                         2.0   
3                         2.0                         2.0   
4                         2.0                         2.0   

   seriousnessdisabling  seriousnesscongenitalanomali  seriousnessother  \
0                   2.0                           2.0               2.0   
1                   2.0                           2.0               2.0   
2                   2.0                           2.0               1.0   
3                   2.0                           2.0               2.0   
4                   2.0                           2.0               1.0   

   patientonsetage  patientonsetageunit  patientsex  \
0             43.0                801.0         2.0   
1             73.0                801.0         2.0   
2             26.0                801.0         2.0   
3             49.0                801.0         2.0   
4             69.0                801.0         1.0   

                                    reactionmeddrapt medicinalproduct  \
0  Cough, Drug specific antibody present, Drug in...           HUMIRA   
1                                      Ear infection         COSENTYX   
2  Autism spectrum disorder, Mucous stools, Gastr...         DUPIXENT   
3        Device issue, Injury associated with device           HUMIRA   
4                                  Colorectal cancer           ZANTAC   

        activesubstancename  
0                ADALIMUMAB  
1               SECUKINUMAB  
2                 DUPILUMAB  
3                ADALIMUMAB  
4  RANITIDINE HYDROCHLORIDE

In [3]:
df.describe()

serious  seriousnessdeath  seriousnesslifethreatening  \
count  12000.000000      11476.000000                11456.000000   
mean       1.430583          1.918961                    1.982804   
std        0.495179          0.272906                    0.130008   
min        1.000000          1.000000                    1.000000   
25%        1.000000          2.000000                    2.000000   
50%        1.000000          2.000000                    2.000000   
75%        2.000000          2.000000                    2.000000   
max        2.000000          2.000000                    2.000000   

       seriousnesshospitalization  seriousnessdisabling  \
count                11580.000000          11416.000000   
mean                     1.840155              1.988174   
std                      0.366478              0.108105   
min                      1.000000              1.000000   
25%                      2.000000              2.000000   
50%                      2.000000              2.000000   
75%                      2.000000              2.000000   
max                      2.000000              2.000000   

       seriousnesscongenitalanomali  seriousnessother  patientonsetage  \
count                  11420.000000      11666.000000      6894.000000   
mean                       1.998511          1.562661       118.922831   
std                        0.038556          0.496079      1262.466732   
min                        1.000000          1.000000         0.000000   
25%                        2.000000          1.000000        44.000000   
50%                        2.000000          2.000000        58.000000   
75%                        2.000000          2.000000        69.000000   
max                        2.000000          2.000000     33649.000000   

       patientonsetageunit   patientsex  
count          6893.000000  10368.00000  
mean            801.006383      1.59973  
std               0.230357      0.49037  
min             800.000000      0.00000  
25%             801.000000      1.00000  
50%             801.000000      2.00000  
75%             801.000000      2.00000  
max             804.000000      2.00000

In [4]:
df.shape

(12000, 15)

In [5]:
df.isna().sum()

safetyreportid                     0
primarysourcecountry             107
serious                            0
seriousnessdeath                 524
seriousnesslifethreatening       544
seriousnesshospitalization       420
seriousnessdisabling             584
seriousnesscongenitalanomali     580
seriousnessother                 334
patientonsetage                 5106
patientonsetageunit             5107
patientsex                      1632
reactionmeddrapt                   0
medicinalproduct                   0
activesubstancename               41
dtype: int64

In [6]:
new_df = df[["safetyreportid", "patientonsetage", "patientsex", "medicinalproduct", "activesubstancename", "reactionmeddrapt"]].copy()

In [7]:
new_df.head()

safetyreportid  patientonsetage  patientsex medicinalproduct  \
0       20401550             43.0         2.0           HUMIRA   
1       20719436             73.0         2.0         COSENTYX   
2       20983728             26.0         2.0         DUPIXENT   
3       20401631             49.0         2.0           HUMIRA   
4       20719827             69.0         1.0           ZANTAC   

        activesubstancename                                   reactionmeddrapt  
0                ADALIMUMAB  Cough, Drug specific antibody present, Drug in...  
1               SECUKINUMAB                                      Ear infection  
2                 DUPILUMAB  Autism spectrum disorder, Mucous stools, Gastr...  
3                ADALIMUMAB        Device issue, Injury associated with device  
4  RANITIDINE HYDROCHLORIDE                                  Colorectal cancer

In [8]:
new_df.isna().sum()

safetyreportid            0
patientonsetage        5106
patientsex             1632
medicinalproduct          0
activesubstancename      41
reactionmeddrapt          0
dtype: int64

In [9]:
mean = new_df["patientonsetage"].mean()
new_df["patientonsetage"].fillna(value=mean, inplace=True)

In [10]:
new_df.dropna(inplace=True)

In [11]:
new_df.isna().sum()

safetyreportid         0
patientonsetage        0
patientsex             0
medicinalproduct       0
activesubstancename    0
reactionmeddrapt       0
dtype: int64

In [12]:
new_df.shape

(10336, 6)

In [13]:
reaction = dict()
for effect in new_df['reactionmeddrapt']:
    for r in effect.split(", "):
        if reaction.get(r.lower()):
            reaction[r.lower()]+=1
        else:
            reaction[r.lower()]=1

In [14]:
reactionList = {}
i = 1
for (k,v) in reaction.items():
    if(v>=80):
        reactionList[k] = i
        i+=1
reactionList["others"] = i

In [15]:
len(reactionList)

61

In [16]:
drug = dict()
for med in new_df['medicinalproduct']:
    for m in med.split(", "):
        if drug.get(m.lower()):
            drug[m.lower()]+=1
        else:
            drug[m.lower()]=1

In [17]:
drugList = {}
i = 1
for (k,v) in drug.items():
    if(v>=70):
        drugList[k] = i 
        i+=1
drugList["others"] = i

In [18]:
print(len(drugList))

29


In [19]:
print(drugList)

{'humira': 1, 'cosentyx': 2, 'dupixent': 3, 'zantac': 4, 'prednisone': 5, 'pomalyst': 6, 'orencia': 7, 'methotrexate': 8, 'cimzia': 9, 'remicade': 10, 'rinvoq': 11, 'trulicity': 12, 'gilenya': 13, 'aspirin': 14, 'lantus solostar': 15, 'moderna covid-19 vaccine': 16, 'opsumit': 17, 'eliquis': 18, 'ibrance': 19, 'eligard': 20, 'pfizer-biontech covid-19 vaccine': 21, 'oxycontin': 22, 'letrozole': 23, 'esbriet': 24, 'vedolizumab': 25, 'entresto': 26, 'neulasta': 27, 'cabometyx': 28, 'others': 29}


In [20]:
print(reactionList)

{'cough': 1, 'drug ineffective': 2, 'nasopharyngitis': 3, 'product use issue': 4, 'device issue': 5, 'colorectal cancer': 6, 'headache': 7, 'decreased appetite': 8, 'pyrexia': 9, 'nausea': 10, 'pain in extremity': 11, 'alopecia': 12, 'fatigue': 13, 'diarrhoea': 14, 'incorrect dose administered': 15, 'injection site pain': 16, 'wrong technique in product usage process': 17, 'prostate cancer': 18, 'dizziness': 19, 'product use in unapproved indication': 20, 'injection site haemorrhage': 21, 'back pain': 22, 'insomnia': 23, 'asthenia': 24, 'abdominal discomfort': 25, 'hypertension': 26, 'off label use': 27, 'rash': 28, 'pain': 29, 'malaise': 30, 'arthralgia': 31, 'cerebrovascular accident': 32, 'product dose omission issue': 33, 'drug dependence': 34, 'death': 35, 'abdominal pain upper': 36, 'constipation': 37, 'hospitalisation': 38, 'covid-19': 39, 'condition aggravated': 40, 'pruritus': 41, 'vomiting': 42, 'therapy interrupted': 43, 'dyspnoea': 44, 'anxiety': 45, 'weight increased': 46,

In [21]:
reactiondict = {key: [0]*len(new_df) for key in reactionList.keys()}
for i, effect in enumerate(new_df["reactionmeddrapt"]):
    reactions = effect.split(", ")
    found = False
    for k in reactions:
        if k.lower() in reactionList.keys():
            reactiondict[k.lower()][i] = 1
            found = True
    if not found:
        reactiondict["others"][i] = 1

In [22]:
print(sum(reactiondict["others"]))

4476


In [23]:
drugdict = {key: [0]*len(new_df) for key in drugList.keys()}
for i, drug in enumerate(new_df["medicinalproduct"]):
    drugs = drug.split(", ")
    found = False
    for k in drugs:
        if k.lower() in drugList.keys():
            drugdict[k.lower()][i] = 1
            found = True
    if not found:
        drugdict["others"][i] = 1

In [24]:
print(sum(drugdict["others"]))

5028


In [25]:
for k,v in drugdict.items():
    new_df[k] = v

In [26]:
X = new_df.drop(["safetyreportid", "medicinalproduct", "activesubstancename", "reactionmeddrapt"], axis=1)

In [27]:
X.shape

(10336, 31)

In [28]:
X.head()

patientonsetage  patientsex  humira  cosentyx  dupixent  zantac  \
0             43.0         2.0       1         0         0       0   
1             73.0         2.0       0         1         0       0   
2             26.0         2.0       0         0         1       0   
3             49.0         2.0       1         0         0       0   
4             69.0         1.0       0         0         0       1   

   prednisone  pomalyst  orencia  methotrexate  ...  eligard  \
0           0         0        0             0  ...        0   
1           0         0        0             0  ...        0   
2           0         0        0             0  ...        0   
3           0         0        0             0  ...        0   
4           0         0        0             0  ...        0   

   pfizer-biontech covid-19 vaccine  oxycontin  letrozole  esbriet  \
0                                 0          0          0        0   
1                                 0          0          0        0   
2                                 0          0          0        0   
3                                 0          0          0        0   
4                                 0          0          0        0   

   vedolizumab  entresto  neulasta  cabometyx  others  
0            0         0         0          0       0  
1            0         0         0          0       0  
2            0         0         0          0       0  
3            0         0         0          0       0  
4            0         0         0          0       0  

[5 rows x 31 columns]

In [29]:
y = pd.DataFrame(reactiondict)

In [30]:
y.shape

(10336, 61)

In [31]:
y.head()

cough  drug ineffective  nasopharyngitis  product use issue  device issue  \
0      1                 1                1                  0             0   
1      0                 0                0                  0             0   
2      0                 0                0                  1             0   
3      0                 0                0                  0             1   
4      0                 0                0                  0             0   

   colorectal cancer  headache  decreased appetite  pyrexia  nausea  ...  \
0                  0         0                   0        0       0  ...   
1                  0         0                   0        0       0  ...   
2                  0         0                   0        0       0  ...   
3                  0         0                   0        0       0  ...   
4                  1         0                   0        0       0  ...   

   urinary tract infection  pneumonia  visual impairment  bladder cancer  \
0                        0          0                  0               0   
1                        0          0                  0               0   
2                        0          0                  0               0   
3                        0          0                  0               0   
4                        0          0                  0               0   

   gait disturbance  renal cancer  weight decreased  peripheral swelling  \
0                 0             0                 0                    0   
1                 0             0                 0                    0   
2                 0             0                 0                    0   
3                 0             0                 0                    0   
4                 0             0                 0                    0   

   no adverse event  others  
0                 0       0  
1                 0       1  
2                 0       0  
3                 0       0  
4                 0       0  

[5 rows x 61 columns]

In [44]:
X_train.values[0]

array([118.92283145,   2.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   1.        ])

In [46]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8268 entries, 6543 to 8433
Data columns (total 31 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   patientonsetage                   8268 non-null   float64
 1   patientsex                        8268 non-null   float64
 2   humira                            8268 non-null   int64  
 3   cosentyx                          8268 non-null   int64  
 4   dupixent                          8268 non-null   int64  
 5   zantac                            8268 non-null   int64  
 6   prednisone                        8268 non-null   int64  
 7   pomalyst                          8268 non-null   int64  
 8   orencia                           8268 non-null   int64  
 9   methotrexate                      8268 non-null   int64  
 10  cimzia                            8268 non-null   int64  
 11  remicade                          8268 non-null   int64  
 12  rin

In [53]:
X = X.drop(["patientsex","patientonsetage"], axis=1)
X.values[0]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support, accuracy_score, precision_score, recall_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

In [54]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
Y_test = Y_test.values 

In [ ]:
clf = LogisticRegression(solver='lbfgs', max_iter=400)
multi_target_lr = MultiOutputClassifier(clf)
multi_target_lr.fit(X_train, Y_train)

In [ ]:
Y_pred = multi_target_lr.predict(X_test)

acc_score, rec_score = 0., 0.
Accuracy_lr = []
Recall_lr = []
for i in range(y_test.shape[0]):
    acc_score += accuracy_score(y_test[i],Y_pred[i])
    Accuracy_lr.append(acc_score)
    rec_score += recall_score(y_test[i],Y_pred[i])
    Recall_lr.append(rec_score)

acc_score = acc_score/y_test.shape[0]
rec_score = rec_score/y_test.shape[0]

print('Accuracy : %.4f%%, \t, Recall : %.4f%%' %(acc_score, rec_score))

Accuracy : 0.9886%, 	, Recall : 0.0143%


In [57]:
import joblib

In [ ]:
joblib.dump(multi_target_lr, "model.h5")

['model.h5']

In [ ]:
mdl = joblib.load("model.h5")

In [55]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=38)
multi_target_knn = MultiOutputClassifier(clf)
multi_target_knn.fit(X_train, Y_train)

MultiOutputClassifier(estimator=KNeighborsClassifier(n_neighbors=38))

In [58]:
# save model 
joblib.dump(multi_target_knn, "model_knn.h5")  
multi_target_knn = joblib.load("model_knn.h5")

In [60]:
Y_test.shape

(2068, 61)

In [59]:
Y_pred = multi_target_knn.predict(X_test)

acc_score, rec_score = 0., 0.
Accuracy_lr = []
Recall_lr = []
for i in range(Y_test.shape[0]):
    acc_score += accuracy_score(Y_test[i],Y_pred[i])
    Accuracy_lr.append(acc_score)
    rec_score += recall_score(Y_test[i],Y_pred[i])
    Recall_lr.append(rec_score)

acc_score = acc_score/Y_test.shape[0]
rec_score = rec_score/Y_test.shape[0]

print('Accuracy : %.4f%%, \t, Recall : %.4f%%' %(acc_score, rec_score))

KeyError: 0

In [39]:
X_test.shape

(2068, 31)

In [68]:
a = X_test.values[13].reshape(1,29)
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0]])

In [63]:
def predict(X_test):

   values = ['cough',
 'drug ineffective',
 'nasopharyngitis',
 'product use issue',
 'device issue',
 'colorectal cancer',
 'headache',
 'decreased appetite',
 'pyrexia',
 'nausea',
 'pain in extremity',
 'alopecia',
 'fatigue',
 'diarrhoea',
 'incorrect dose administered',
 'injection site pain',
 'wrong technique in product usage process',
 'prostate cancer',
 'dizziness',
 'product use in unapproved indication',
 'injection site haemorrhage',
 'back pain',
 'insomnia',
 'asthenia',
 'abdominal discomfort',
 'hypertension',
 'off label use',
 'rash',
 'pain',
 'malaise',
 'arthralgia',
 'cerebrovascular accident',
 'product dose omission issue',
 'drug dependence',
 'death',
 'abdominal pain upper',
 'constipation',
 'hospitalisation',
 'covid-19',
 'condition aggravated',
 'pruritus',
 'vomiting',
 'therapy interrupted',
 'dyspnoea',
 'anxiety',
 'weight increased',
 'inappropriate schedule of product administration',
 'feeling abnormal',
 'emotional distress',
 'illness',
 'fall',
 'urinary tract infection',
 'pneumonia',
 'visual impairment',
 'bladder cancer',
 'gait disturbance',
 'renal cancer',
 'weight decreased',
 'peripheral swelling',
 'no adverse event',
 'others']
 
   y_pred = multi_target_knn.predict(X_test)
   print(y_pred)
   y_pred = np.argmax(y_pred, axis=1)  
   print(y_pred)
   return values[y_pred[0]]

In [69]:
#ignore warnings 
import warnings
warnings.filterwarnings('ignore')

predict(a)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[0]


'cough'

In [ ]:
X_test

patientonsetage  patientsex  humira  cosentyx  dupixent  zantac  \
7728        52.000000         2.0       0         0         0       0   
7084        55.000000         1.0       0         0         0       0   
887         56.000000         2.0       0         0         0       0   
5694       118.922831         2.0       1         0         0       0   
645         87.000000         2.0       0         0         0       0   
...               ...         ...     ...       ...       ...     ...   
7865        38.000000         2.0       0         0         0       0   
9075        21.000000         1.0       0         0         0       0   
5319        67.000000         2.0       0         0         0       0   
7539        54.000000         2.0       0         0         0       0   
4475        44.000000         2.0       0         0         0       0   

      prednisone  pomalyst  orencia  methotrexate  ...  eligard  \
7728           0         0        0             0  ...        0   
7084           0         0        0             0  ...        0   
887            0         0        0             0  ...        0   
5694           0         0        0             0  ...        0   
645            0         0        0             0  ...        0   
...          ...       ...      ...           ...  ...      ...   
7865           0         0        0             0  ...        0   
9075           0         0        0             0  ...        0   
5319           0         0        0             0  ...        0   
7539           0         0        0             0  ...        0   
4475           0         0        0             0  ...        0   

      pfizer-biontech covid-19 vaccine  oxycontin  letrozole  esbriet  \
7728                                 0          0          0        0   
7084                                 1          0          0        0   
887                                  0          0          0        0   
5694                                 0          0          0        0   
645                                  0          0          0        0   
...                                ...        ...        ...      ...   
7865                                 0          0          0        0   
9075                                 0          0          0        0   
5319                                 0          0          1        0   
7539                                 0          0          0        0   
4475                                 0          0          0        0   

      vedolizumab  entresto  neulasta  cabometyx  others  
7728            0         0         0          0       1  
7084            0         0         0          0       0  
887             0         0         0          0       0  
5694            0         0         0          0       0  
645             0         0         0          0       1  
...           ...       ...       ...        ...     ...  
7865            0         0         0          0       1  
9075            0         0         0          0       1  
5319            0         0         0          0       0  
7539            0         0         0          0       0  
4475            0         0         0          0       1  

[2068 rows x 31 columns]

In [ ]:
Y_test[4]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# make predictions 
y_pred = multi_target_knn.predict(X_test)
y_pred

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
Y_pred[9]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
Y_test[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
Y_test[205]

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [ ]:
clf = RandomForestClassifier(n_estimators=300, criterion = 'gini', max_depth=60, random_state=None)
multi_target_forest = MultiOutputClassifier(clf)
multi_target_forest.fit(X_train, Y_train)

MultiOutputClassifier(estimator=RandomForestClassifier(max_depth=60,
                                                       n_estimators=300))

In [ ]:
import warnings
warnings.filterwarnings('ignore')

Y_pred = multi_target_forest.predict(X_test)

# Initialize variables
acc_score, prec_score, rec_score = 0., 0., 0.
Accuracy_RF = []
Precision_RF = []
Recall_RF = []
for i in range(Y_test.shape[0]):
    acc_score  += accuracy_score(Y_test[i],Y_pred[i])
    Accuracy_RF.append(acc_score)
    prec_score += precision_score(Y_test[i],Y_pred[i])
    Precision_RF.append(prec_score)
    rec_score  += recall_score(Y_test[i],Y_pred[i])
    Recall_RF.append(rec_score)

acc_score  = acc_score/Y_test.shape[0]
prec_score = prec_score/Y_test.shape[0]
rec_score  = rec_score/Y_test.shape[0]

print('Accuracy : %.4f%%, \t Precision : %.4f%%, \t, Recall : %.4f%%' %(acc_score, prec_score, rec_score))

Accuracy : 0.9816%, 	 Precision : 0.0997%, 	, Recall : 0.0935%


In [ ]:
# Get the prediction for the first row of the test set
# (The first row of the test set is at index 0, so we use 0 as the index.)
Y_pred[0]